### ISSUE TITLE
Research existing solutions

### ISSUE THREAD

**Issue by valiafetisov** [powerhouse-inc/switchboard-boilerplate#2]
### Goal

Overview on the existing tools that we can use

### Context

During the initial planning, we raised the questions and mentioned few existing solutions which might cover some of the requirements. Those include [sanity](https://www.sanity.io/graphql), [strapi](https://strapi.io/), [slicknode](https://github.com/slicknode/slicknode) for headless CMSs and [postgraphile](https://github.com/graphile/postgraphile) and [graphile](https://www.graphile.org/) for automatically generated graphql endpoints.

### Tasks

- [x] Evaluate existing tools, initially proposed and newly discovered
  - [x] Check their applicability to the raised requirements
  - [x] Check their licences
- [ ] Conclude the very initial technical stack

**Comment by valiafetisov** [comment]
### Headless CMSs

- [**Sanity**](https://www.sanity.io/graphql) – "GraphQL Headless CMS"
    - [MIT License](https://github.com/sanity-io/sanity/blob/next/LICENSE)
    - Cons
        - Only the [frontend/app](https://github.com/sanity-io/sanity) is open-source, but backend is not
        - They doesn't even advertise what database they use, seems to be graph-based
- [**Strapi**](https://github.com/strapi/strapi) – "open-source headless CMS"
    - [MIT Expat License](https://github.com/strapi/strapi/blob/main/LICENSE)
    - Available as completely self-hosted "community edition"
        - [Getting-started page](https://docs.strapi.io/developer-docs/latest/getting-started/quick-start.html)
    - Pros
        - ✔️ Supports `sqlite` or `postgres` or `mysql` as the data storage
        - ✔️ Have REST as well as graphql API endpoints out of the box
        - ✔️ Have API token generation with granular roles available
        - `+/-` Have user roles out of the box
            - But they are limited to 3 default one (that's their main selling feature for the paid version) – I think workaround/extensions are possible, since the source code is available
        - ✔️ UI for creating, editing, deleting of records (+ optional draft/publication of records)
        - Other
            - (optional) UI for creating, editing and deleting tables (available only to superadmins), although the change is stored as a code change, not in the database! So git-based review process is required to modify database structure and the models
                - it is possible to extend models with custom logic
                - [Migrations are possible](https://docs.strapi.io/developer-docs/latest/developer-resources/database-migrations.html) but are using `knex` and written in js
            - Webhooks on content edit event
            - File upload (to AWS S3 / locally)
            - Custom plugin support
            - Even record history seems to be possible: https://www.youtube.com/watch?v=AsEGCzFiWTM
    - Cons
        - User roles limited to 3, workaround is needed
        - Mostly js-based, but [typescript support can be added](https://docs.strapi.io/developer-docs/latest/development/typescript.html#start-developing-in-typescript) (but not sure if migrations can be written in typescript though)
        - In the past (~1.5 year ago) we had not so good experience with it due to internal bugs and breaking changes
- [**Slicknode**](https://github.com/slicknode/slicknode) – "GraphQL Backend, Gateway, and Headless CMS"
    - [OSL-3.0 License](https://github.com/slicknode/slicknode/blob/master/LICENSE)
    - Available as "self-hosted" version
        - [Getting-started page](https://slicknode.com/docs/quickstart/)
    - Cons
        - Require "slicknode account" to create project (according to the [video demo](https://youtu.be/VGpm6J-0dKg?t=39))
        - The content is also managed via external interface

### Automatically generated graphql endpoints from SQL database

- [**PostGraphile**](https://github.com/graphile/postgraphile) – "GraphQL API for your PostgreSQL database"
    - [MIT License](https://github.com/graphile/postgraphile/blob/main/LICENSE.md)
    - Pros
        - ✔️ Supports PostgreSQL
        - ✔️ Directly generates rules based on the SQL schema (so independent of the ORM used)
        - ✔️ Can work as Express/Koa middleware (so be part of a single codebase)
            - Or as a standalone service [via a cli](https://www.graphile.org/postgraphile/usage-cli/)
        - Support custom queries, mutations, computed columns 
            - (typically via [postgres functions](https://www.graphile.org/postgraphile/custom-queries/))
            - But can be circumvent [via a plugin](https://github.com/graphile-contrib/postgraphile-plugin-derived-field)
        - Provides programmatic access to [generated schema](https://www.graphile.org/postgraphile/usage-schema/)
        - Use SQL comments
    - Cons
        - `+/-` Authorization can be derived from "PostgreSQL's RBAC and Row-Level Security"
            - So we would need to have ORM that supports that or implement auth ourselves via another middleware or via their [extensive plugin system](https://www.graphile.org/postgraphile/community-plugins/)
        - Highly dependent on the database (and database "smart comments") which is probably possible to circumvent via plugins
- [**Hasura**](https://github.com/hasura/graphql-engine) - "GraphQL APIs on your DB with fine grained access control, webhooks on database events"
    - Core under [Apache License 2.0](https://github.com/hasura/graphql-engine/blob/master/LICENSE), [everything else under the MIT License](https://github.com/hasura/graphql-engine#license)
    - Pros
        - ✔️ Supports PostgreSQL
        - ✔️ Automatically creates both GraphQL and/or [REST APIs](https://hasura.io/docs/latest/api-reference/restified/)
        - Extendible schema with custom business logic
            -  :( ([via external APIs](https://hasura.io/docs/latest/actions/create/))
        - Webhooks on database events
            -  :( ([via calling external APIs](https://github.com/hasura/graphql-engine/blob/master/event-triggers.md))
        - Derived data or data transformations
            -  :( ([via postgres functions/computed fields](https://hasura.io/docs/latest/schema/postgres/computed-fields/)) 
        - Doesn't provide [authorisation by itself](https://hasura.io/docs/latest/auth/index/) (needs to be implemented by us)
    - Cons
        - `+/-` Basically an encapsulated service extensible only via configuration and calls to other services
        - Might have some reliance/connection to their cloud-based frontend ([but probably not, based on this tutorial](https://medium.com/@jeff_long/simple-self-hosted-hasura-cb541b023c83))

### Bare tools

- [**TypeORM**](https://github.com/typeorm/typeorm) - ORM for TypeScript
    - [MIT License](https://github.com/typeorm/typeorm/blob/master/LICENSE)
    - Pros
        - Supports two different patterns of writing models [Active Record vs Data Mapper](https://github.com/typeorm/typeorm/blob/HEAD/docs/active-record-data-mapper.md#what-is-the-active-record-pattern)
            - We probably should use `Data Mapper` pattern [with custom repositories](https://github.com/typeorm/typeorm/blob/master/docs/custom-repository.md)?

- [**TypeGraphQL**](https://github.com/MichalLytek/type-graphql) - A library to create graphql schema from the code (so it doesn't need to be maintained separately)
    - [MIT License](https://github.com/MichalLytek/type-graphql/blob/master/LICENSE)
    - Pros
        - No need to write queries manually and separately maintain them, [blog post about it and a tutorial](https://blog.logrocket.com/build-graphql-typegraphql-typeorm/)
        - Good integration with typeorm (schema is automatically derived from models)
        - Great flexibility as views/calculated columns can be added via typeorm itself
    - Cons
        - Still requires a bit overhead to declare schemas (compared to automatic generation)
            - But this allow us more granular control
            - Can be circumvented programmatically (eg loop over all models)

### Overall

Automatically generated GraphQL APIs on top of the database is probably not a good contender, since it heavily depends on database structure, database functions, authorisation rules and comments, which we wanted to avoid in the first place. Working programmatically with those database features can be challenging and moreover less testable.

`Strapi` seems to be a strong candidate that covers most of the basic requirements out of the box and allow extensions. One problem is non-native typescript support, where not everything can be written in typescript and the platform itself is written in plain javascript. The other problem is extensibility of the frontend, which is not as flexible as backend and framework-dependent. It's good to quickly kick-start a simple project, but can become a nightmare with very custom features.

The other approach would be to set up a clear declarative-style structure ourselves, using `TypeGraphQL` on top of `TypeORM` – two very popular typescript-native libraries which will cover most of the basic "repetitive code" problems out of the box. But to reach level of the `Strapi` functionality, we would need to add our own authorisation library and a simple frontend to manage users, generate tokens and preview the data. I am favouring this option the most at the moment

**Comment by BracketJohn** [comment]
> But

"But", in rejection of what?

Other remarks:
- what about Prisma ORM?
  - My pre-opinion is that it likely also does not fit our use case: It requires a complex build-step that will be hard to impossible to modularize in the way that we discussed with @wkampmann 
  - still let's have a quick look - maybe something in the area of multi-schema support or similar has changed in recent months
- what about knex.js - the currently used DB lib?
- observation: It seems to me that the problem with all of the CMSs is their "centralization": extending them in the community-module-style we imagined always seems to be part of "the catch" of why we can't use them - very interesting

>  Conclude the very initial technical stack

what I'm missing here at the moment to come to a conclusion is a set of requirements that we have that these tools will help us with. I know we have it in docs and issues elsewhere - can you link them / do a high-level overview of the requirements here or in a dedicated issue as well, so that we can reach a more grounded decision?

**Comment by valiafetisov** [comment]
Good points, thank you! 

> what I'm missing here at the moment to come to a conclusion is a set of requirements

You're right, [those are the initial requirements](https://github.com/makerdao-ses/switchboard-boilerplate/issues/3#issuecomment-1437098636) I've just put together based on the existing input. Feel free to comment there as well!

But please note, the initial purpose of the current issue was to investigate, if we can use use any existing headless ORMs. And I think the conclusion is clear: we better not if we want to keep flexibility for the long-term features. I agree about spending more time on other "bare tools" and will more thoroughly look into `typeorm` competitors like `prisma`, `knex.js`, [`nexus`](https://github.com/graphql-nexus/nexus), etc

**Comment by valiafetisov** [comment]
I've added 5 more libraries to the [`Bare tools` section above](https://github.com/makerdao-ses/switchboard-boilerplate/issues/2#issuecomment-1433057159) and further specified requirements in #3. I think my conclusion stands the same, although `MikroORM` looks interesting (but also less popular/less integrated). Let me know if you want to see other tools in the list

**Comment by BracketJohn** [comment]
>  It requires a complex build-step that will be hard to impossible to modularize 

Prisma update: Actually, they have client-side extensions now: This is quite nice as it adds typed alterations to the prisma client. This also allows to implement computed properties: https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions

**Comment by BracketJohn** [comment]
> Flexibility. My main fear is that because Prisma models have to be pre-compiled, we might end up with essential feature that they simply don't support yet, or a feature the support of which they will drop one day? Don't have a good example for this yet (maybe enums?)

agreed - with an open end project like this it is probably best to keep all options open

> Prisma instead suggests to [Wrap a Prisma Model in a Class](https://www.prisma.io/docs/concepts/components/prisma-client/custom-models#wrap-a-prisma-model-in-a-class) (but [client extensions](https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions) feature might also help here, they just didn't add it to the same guide):

I think here Prisma is actually on the same level as typeORM with the recent extensions feature. If you look at the docs of this you'll see that you can modify behavior on most levels. I think this should be neough.


> The ability to dynamically define model. I expect that the end goal of this product (development-wise) is to make a declarative-like interface where in some file we just define how this particular model behaves on a business-level and then everything else is geneated: the endpoints, the interfaces, input validators, etc. For this to work, I expect that we will need to extend or come up with our own declarative structure that will require necessary fields and "dynamically" generated models based on that.

where is this requirement from?

> Split logic info different module folders

as outlined orally: I have not seen this actually happening in https://github.com/makerdao-ses/ecosystem-api instead I've seen https://github.com/makerdao-ses/ecosystem-api/blob/main/seeds/01-CoreUnits.js as a central definition and then in https://github.com/makerdao-ses/ecosystem-api/tree/main/src/modules/Auth it's only about business logic -> where do you get this requirement from?

> Virtual columns

as above: this should be resolved by `client-extensions` (you also write this, I just want to make clear that in my eyes the two solutions are on the same level here)

---

doing a summary here: I see that in point (1), (3) (if actual requirement), (4) (if actual requirement) typeorm leads. If 3 and 4 are both not requirements it would boil down to (1).

what about considerations like developer-experience and improved typescript support, both of which are probably important to external contributors?

**Comment by valiafetisov** [comment]
> I think here Prisma is actually on the same level as typeORM with the recent extensions feature

Agree with this, extensions feature is quite nice. Although the interface is not as friendly as a wide variety of decorators

>> The ability to dynamically define model.
>
> where is this requirement from?

There is a requirement to build document interface for every kind of document and every kind of action on top of this document. From this I derive that we would rather make a declarative structure where the interface is generated from it, instead of forcing to implement the UI/validators separately separately for each model and force external developers to do it every time they submit a change.

>> Split logic info different module folders
>
> where do you get this requirement from?

This was raised during the meeting with Wouter. As far as I understood, [ecosystem-api](https://github.com/makerdao-ses/ecosystem-api) should not be eyed as a quality standard, if we can do better. I personally would prefer to keep those things in one place, but also understand that as soon as there relations, you can no longer clearly separate those things

> what about considerations like developer-experience and improved typescript support, both of which are probably important to external contributors?

Overall, I see _no major differences_ here, some things just done differently here vs there. There is also no much difference features-wise (4 is really no a very big deal), but the only real considerations for me here were 1 and 3.

**Comment by ridafkih** [comment]
Not sure what this is about as I'm just here to the reference on an issue on the Prisma repository, but if y'all need dynamically generated Prisma schémas, I have a library on my profile which would let you generate them programatically. 😂
