### ISSUE TITLE
Setup CI/CD pipeline in new git org

### ISSUE THREAD

**Issue by LukSteib** [powerhouse-inc/switchboard-boilerplate#43]
### Goal
Move repo and properly setup CI/CD

### Context
The switchboard API is going to be part of the broader powerhouse product suite. For that we need to ensure that
- repo is moved to right org
- CI/CD is setup properly for the repo

### Tasks
- [ ] Move this repo to [powerhouse git org](https://github.com/powerhouse-inc)
- [ ] Setup CI/CD for this repo in new org
   - [ ] Ensure that staging deployment works as expected
- [ ] notify @valiafetisov / @LukSteib once done in order to communicate properly with SES for rights removal

**Comment by valiafetisov** [comment]
> Move this repo to [powerhouse git org](https://github.com/powerhouse-inc)

This was done in the meantime!

@DeusAvalon do you now have enough rights to complete the rest of the tasks and switch staging to be triggered by this repo instead of the [sidestream-tech/switchboard-boilerplate](https://github.com/sidestream-tech/switchboard-boilerplate) fork?

**Comment by DeusAvalon** [comment]
Yes i do have the needed permissions now to properly create secrets ect :) I would add the CI/CD (based on our new Argo) to the powerhouse repo by tmrw if the timeframe is ok for you :)

**Comment by valiafetisov** [comment]
Tomorrow by the end of the day would be great!

Do you also have enough rights to give me write rights? It seems like after the repository has been moved I'd lost my regular write rights and can no longer push to the repo 😞

**Comment by DeusAvalon** [comment]
I changed the permissions of the `sidestream` team in the repo to write, so you should have access now :)

**Comment by valiafetisov** [comment]
Closed by #56
