### ISSUE TITLE
Improve documentation integration 

### ISSUE THREAD

**Issue by valiafetisov** [powerhouse-inc/switchboard-boilerplate#57]
### Goal
Implement dynamic `document-model-libs` documentation

### Context
As all changes [proposed in the initial issue](https://github.com/powerhouse-inc/switchboard-boilerplate/issues/22#issuecomment-1508379896) were [reported as addressed](https://github.com/powerhouse-inc/switchboard-boilerplate/issues/22#issuecomment-1560803749), it's now our task to update the integration and make it dynamic (so whenever `document-model-libs` is updated, documentation is also updated automatically)

### Tasks
- [x] Add `document-model-libs` as npm package
- [x] Update [`generateDocs` script](https://github.com/powerhouse-inc/switchboard-boilerplate/blob/main/frontend/scripts/generateDocs.ts)
- [ ] Remove initial static md files
- [x] Manually test generation via docker-compose (as it might require additional changes to take md files from `node_modules`)

**Comment by valiafetisov** [comment]
@KirillDogadin-std wrote: 
> not sure what the requirement `remove initial static md files` means in the issue. Could you elaborate what here is wrong if it is?

When writing the issue I thought that we kept initial md files provided to us and already executed `generateDocs.ts` somewhere during frontend build in order to produce `content/documentation/index.md` file. Now I see it's not the case, this particular point can be ignored. 

What I would expect nevertheless, is that `content/documentation/index.md` file is produced automatically from the npm package and doesn't need an additional action from the developer (ie manually running `generateDocs.ts` and then committing generated file is not a desired flow)
