### ISSUE TITLE
Improve developer experience

### ISSUE THREAD

**Issue by valiafetisov** [powerhouse-inc/switchboard-boilerplate#59]
### Goal
Developer is able to start the project without docker, by following simple instruction

### Context
After starting project, Wouter had a few suggestions, which I rephrased as tasks below

### Tasks
- [x] Set default port numbers so that frontend and backend start on different ports by default
  - [x] Docker-compose can still start them separately
  - [x] Set correct graphql URL by default
- [x] Add readme instruction for running without docker
- [x] Add readme how to use postgres (outside of the docker)
- [x] Remove linter rule to allow double quotes (since [nexus SDL converter](https://nexusjs.org/converter) outputs double quotes by default)
- [x] Make sure that docker still works as expected (as well as staging)
- [x] See if there is anything else to improve
