### ISSUE TITLE
Setup ORM

### ISSUE THREAD

**Issue by valiafetisov** [powerhouse-inc/switchboard-boilerplate#6]
### Goal

Repository contains ORM setup with a single table and readme instructions

### Tasks

- [ ] Finalise technical discussion in https://github.com/makerdao-ses/switchboard-boilerplate/issues/2
- [ ] Install ORM
- [ ] Setup database (eg docker-compose if needed)
- [ ] Create first tables and rules
- [ ] Setup playground
- [ ] Update readme with clear instructions on how to start and test

**Comment by BracketJohn** [comment]
So, I think I checked all of these boxes in #12. However, I'll leave this issue open for now, so that we can discuss and maybe still adaopt some decisiobns:
> Finalise technical discussion in https://github.com/makerdao-ses/switchboard-boilerplate/issues/2
