### ISSUE TITLE
Update wundergraph settings after Ecosystem API is ready

### ISSUE THREAD

**Issue by valiafetisov** [powerhouse-inc/switchboard-boilerplate#66]
### Goal
Ecosystem API is composed together with the rest of the queries

### Context
After implementation of the [migration strategy](https://github.com/powerhouse-inc/switchboard-boilerplate/issues/60), we're waiting for the [makerdao-ses/ecosystem-api](https://github.com/makerdao-ses/ecosystem-api) to be changed according to the proposal. After that, we should redeploy the same codebase with a new env variable `ECOSYSTEM_GQL_ENDPOINT` to be set to `https://ecosystem-dashboard.herokuapp.com/graphql`.

### Tasks
- [ ] Clearly outline required changes
- [ ] Notify relevant stakeholders
- [ ] Check that changes has been applied
- [ ] Change `ECOSYSTEM_GQL_ENDPOINT` env var
- [ ] Re-trigger the deployment
- [ ] Validate that the endpoints are properly composed together

**Comment by valiafetisov** [comment]
FYI: https://github.com/powerhouse-inc/switchboard-boilerplate/pull/64 was deployed and is accessible [on staging](https://powerhouse.switchboard.k8s.sidestream.tech/graphql-playground). Currently the API is composed together with example graphql endpoint `https://countries.trevorblades.com/graphql` (with enabled cors and introspection). To test composition, one can:
1. Open https://powerhouse.switchboard.k8s.sidestream.tech/graphql-playground
2. Set server url to be `https://powerhouse.switchboard.k8s.sidestream.tech/wundergraph/graphql`
3. Execute `query { coreUnits {id} ecosystem_countries {code}}`
