### ISSUE TITLE
Setup main branch protection

### ISSUE THREAD

**Issue by BracketJohn** [powerhouse-inc/switchboard-boilerplate#7]
## Goal

Ensure that the main branch is protected

## Tasks

- [ ] add branch protection to `main`
  - [ ] require review
  - [ ] require checks passing (we have a basic github CI that will be extended later but can be referenced already)
  - [ ] require linear history
  - [ ] dismiss stale reviews automatically

**Comment by BracketJohn** [comment]
@wkampmann: please either do this yourself or give me and/or @valiafetisov the rights to setup branch protection. Thanks!
